(define (* a b)
  (define (double val)
    (+ val val))
  (define (halve val)
    (/ val 2))
  (define (inner a b)
    (cond ((= b 0) 0)
          ((= b 1) a)
          ((even? b) (inner (double a) (halve b)))
          (else (+ a (inner a (- b 1))))))
  (if (< b a)
      (inner a b)
      (inner b a)))


(and (= (* 2 3) 6)
     (= (* 10 4) 40)
     (= (* 5 5) 25)
     (= (* 1 7) 7)
     (= (* 0 1) 0)
     (= (* 1 0) 0))
